### ISSUE TITLE
Allow decimal (cents) for salaries in reviews

### ISSUE THREAD

**Issue by SGinovker** [alexieyizhe/intern.plus#125]
When submitting a review, salary must be an integer. I think having the ability to add decimals is important, because 22.50 vs 22 hourly rate can make a difference over 4 month coops.

**Comment by alexieyizhe** [comment]
Hey @SGinovker, sorry for the delayed reply, just finished my last exam :)

This is something I considered when designing the site, but didn't end up doing for a number of reasons:

- Monthly/weekly salaries are almost always round integer values
- An hourly rate difference of +-50 cents, which is the largest difference in decimal vs rounded form, works out to around a 300 dollar difference over a work term. While it is a decent chunk of money, it feels to me less significant relative to the overall salary, and the rest of the information that's available if you're trying to compare companies.
- Displaying decimal values clutters up the UI a bit
- This is only relevant now, but changing the backend and frontend to account for cents is a fair bit of work that I would prioritize other features over.

That being said, if the user feedback is that it would be much more useful, I'm open to the idea and will keep it in mind working on this in the future 👍

**Comment by alexieyizhe** [comment]
Closing this for now!
