### ISSUE TITLE
Add autocomplete suggestions for company search textbox

### ISSUE THREAD

**Issue by MathBunny** [alexieyizhe/intern.plus#37]
It'd be nice to have a dropdown illustrating some of the companies that could be prefixed with the substring already entered in the search box. For example, `Ja` => `Jane Street` or `A` => `Apple, Amazon` etc. 

It'd make searching quicker because if I do `Cit` and `Citadel` doesn't appear, then I know not to search it. Thanks!

**Comment by alexieyizhe** [comment]
This is really interesting and definitely a good quality-of-life improvement for users. I'll put it in my to-dos! Thanks for suggesting it :))

**Comment by MathBunny** [comment]
No problem :)

**Comment by alexieyizhe** [comment]
Heya @MathBunny, the feature's been merged and should be deployed later today :)) try it out and let me know if there are any bugs
