### ISSUE TITLE
Migrate to better backend & db

### ISSUE THREAD

**Issue by alexieyizhe** [alexieyizhe/intern.plus#61]
Current solution may incur excessive costs that I would like to avoid
- Amazon AppSync & Amplify?
- Firebase?
- Custom backend server & db?

**Comment by drdgvhbh** [comment]
If you wanna write a custom server, [Nest.JS](https://docs.nestjs.com/) is probably the best for Node/Typescript ATM. Tons of things out of the box and great documentation

**Comment by alexieyizhe** [comment]
That's a good option, but I think if I was to roll with a custom server, it'd just be simple Express + Apollo Server. Anything more is a bit overkill since it's essentially just serving the database at the moment. 

Thank you for sharing that though!

**Comment by alexieyizhe** [comment]
Closed by #155
