### ISSUE TITLE
How do you startup the graphql server?

### ISSUE THREAD

**Issue by drdgvhbh** [alexieyizhe/intern.plus#63]
Just ran `npm run start` but it doesn't start up the graphql server.

Nothing under the server folder seems to create a graphql server either. 

`REACT_APP_DB_GRAPHQL_API_URL` must also be defined somewhere in my `.env` as well I'm guessing?

**Comment by alexieyizhe** [comment]
Hey! So you're correct in that `REACT_APP_DB_GRAPHQL_API_URL` needs to be defined. Right now, running the project locally hits a test database in the remote DBaaS that I have set up.

You're welcome to set up your own graphQL endpoint and point `REACT_APP_DB_GRAPHQL_API_URL` to it and it should work, provided that you have the correct schema (which can be pieced together from the graphQL queries). 

It's not the most complete setup, and eventually I'm hoping to set up a local mock server and define the schema in code.

**Comment by alexieyizhe** [comment]
I've just merged a pull request that allows for local development without the backend API url. When you spin up the project locally, it should now have mock data generated by `faker`!
