### ISSUE TITLE
"Options" pane causes horizontal scroll bar

### ISSUE THREAD

**Issue by ian-fox** [alexieyizhe/intern.plus#93]
Browser: Firefox 70.0 (64 bit, windows 10)
Steps to reproduce:
* Go to a specific company's page, such as https://intern.plus/companies/cognite
* If "options" pane is popped out, click the arrow to collapse it
* Observe a horizontal scroll bar: ![](https://i.imgur.com/wxv2GJG.png)
* Hover over the "options" pane in the bottom right so that it pops out
* Observe scroll bar is gone: ![](https://i.imgur.com/O7s9BNt.png)

Obviously super minor and probably not a high priority.

**Comment by ian-fox** [comment]
Also, fantastic website! Looks very clean.

**Comment by alexieyizhe** [comment]
Hey! Thanks so much! I can't believe I didn't catch this. I'll put up a PR to fix this soon
